use HotelManagementDB
-- Loại phòng
INSERT INTO LOAIPHONG (TENLOAI, DONGIA) VALUES (N'Phòng đơn', 150000);
INSERT INTO LOAIPHONG (TENLOAI, DONGIA) VALUES (N'Phòng đôi', 200000);
INSERT INTO LOAIPHONG (TENLOAI, DONGIA) VALUES (N'Phòng VIP', 350000);

-- Loại khách
INSERT INTO LOAIKHACH (TENLOAIKHACH) VALUES (N'Nội địa');
INSERT INTO LOAIKHACH (TENLOAIKHACH) VALUES (N'Nước ngoài');

-- Phụ thu (tỷ lệ %)
INSERT INTO PHUTHU (Giatriphuthu) VALUES (25);

-- Nhân viên mẫu
INSERT INTO NHANVIEN (HOTEN, PHAI, NGAYSINH, SDT, EMAIL, DIACHI) 
VALUES (N'Nguyễn Văn A', N'Nam', '1990-05-15', '0901234567', 'admin@gmail.com', N'TP.HCM');
INSERT INTO NHANVIEN (HOTEN, PHAI, NGAYSINH, SDT, EMAIL, DIACHI) 
VALUES (N'Trần Thị B', N'Nữ', '1995-08-20', '0909876543', 'nhanvien01@gmail.com', N'TP.HCM');

-- Tài khoản (Manager dùng @gmail.com, Staff dùng @siu.edu.vn)
INSERT INTO TAIKHOAN (TENTKNV, MKTK, VAITRO, MANV) VALUES ('admin@gmail.com', '123456789', 'ADMIN', 1);
INSERT INTO TAIKHOAN (TENTKNV, MKTK, VAITRO, MANV) VALUES ('nhanvien01@gmail.com', '123456789', 'NHANVIEN', 2);

-- Phòng mẫu
INSERT INTO PHONG (TENPHONG, TINHTRANG, SOLUONGKHACHTOIDA, MALOAIPHONG, SONGAYO)
VALUES (N'P101', 1, 2, 1, 0);
INSERT INTO PHONG (TENPHONG, TINHTRANG, SOLUONGKHACHTOIDA, MALOAIPHONG, SONGAYO)
VALUES (N'P102', 1, 3, 2, 0);
INSERT INTO PHONG (TENPHONG, TINHTRANG, SOLUONGKHACHTOIDA, MALOAIPHONG, SONGAYO)
VALUES (N'P201', 1, 4, 3, 0);